# 站点配置
title:生存分析案例报告
description: 一个简洁优雅的个人博客
author: yue
email: 12311658@sustech.mail.edu.cn

# Jekyll 配置
theme: minima  # GitHub Pages 默认支持的主题
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 站点设置
baseurl: ""  # 如果使用自定义域名，留空
url: "https://lsy1658.github.io"  # 替换为你的 GitHub Pages 地址

# 分页（可选）
paginate: 5
paginate_path: "/page:num/"

# 社交媒体（可选）
social:
  github: yourusername
  twitter: yourusername

# 其他设置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
